







# OrangeFox settings
OF_HIDE_NOTCH := 1
OF_USE_GREEN_LED := 0
# OF_USE_GREEN_LED := 1
OF_FLASHLIGHT_ENABLE := 0
OF_ALLOW_DISABLE_NAVBAR := 0
OF_QUICK_BACKUP_LIST := /boot;/init_boot;/vendor_boot;/vendor_kernel_boot
# OF_QUICK_BACKUP_LIST := /data;/boot;
OF_SKIP_MULTIUSER_FOLDERS_BACKUP := 1
OF_ENABLE_USB_STORAGE := 1
OF_IGNORE_LOGICAL_MOUNT_ERRORS := 1
OF_BIND_MOUNT_SDCARD_ON_FORMAT := 1
OF_FORCE_CASEFOLDING := 1

# OrangeFox GUI settings
OF_SCREEN_H := 2400
OF_STATUS_H := 100
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_CLOCK_POS := 1
OF_OPTIONS_LIST_NUM := 6

# Recovery additional features	
OF_ENABLE_LPTOOLS := 1

OF_DISABLE_OTA_MENU := 1
OF_DYNAMIC_FULL_SIZE := 8531214336

# OTA
OF_NO_TREBLE_COMPATIBILITY_CHECK := 1
# OF_PATCH_AVB20 := 1
OF_KEEP_DM_VERITY_FORCED_ENCRYPTION := 1
OF_MAINTAINER := "LeeGarChat"
OF_DISABLE_MIUI_SPECIFIC_FEATURES := 1
OF_SUPPORT_ALL_BLOCK_OTA_UPDATES := 1



PB_DEVICE_MODEL := shusky



# OF_KEEP_FORCED_ENCRYPTION := 1
# OF_FBE_METADATA_MOUNT_IGNORE := 1
# OF_USE_LEGACY_BATTERY_SERVICES := 1
# OF_DISABLE_FORCED_ENCRYPTION := 1
# OF_DISABLE_DM_VERITY_FORCED_ENCRYPTION := 1
# OF_DISABLE_DM_VERITY := 1
# OF_USE_MAGISKBOOT := 1
# OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := 1
# OF_RUN_POST_FORMAT_PROCESS := 1
# OF_USE_LZ4_COMPRESSION := 1 
# OF_DONT_KEEP_LOG_HISTORY := 1
# OF_ENABLE_FS_COMPRESSION := 1
